---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- name: Get master node address
  set_fact:
    rabbitmq_master: "{{ hostvars[groups[rabbitmq_hosts_group][0]]['ansible_hostname'] }}"
  when: rabbitmq_master is not defined

- include: install.yml

- include: configure.yml

- include: cleanup.yml
  when: rabbitmq_installed.changed and rabbitmq_cluster

- name: Ensure RabbitMQ is running
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

# Create these before users, so that users can belong to new vhosts
- include: vhosts.yml

- include: users_and_plugins.yml

- include: exchanges.yml

- include: cluster.yml
  when: ansible_hostname != rabbitmq_master and rabbitmq_cluster

- include: metrics.yml
  when: rabbitmq_metrics
